### ISSUE TITLE
Use :latest Docker image tag in README

### ISSUE THREAD

**Issue by hjacobs** [zalando/typhoon#106]
For convenience change the command to (saves the user from looking up the release version):

```
docker run -d -p 8080:8080 registry.opensource.zalan.do/hunt/typhoon:latest
```

Pier One (our OSS registry) supports the virtual `latest` tag since last year. It was never officially announced as it should not be used for deployments, but for such a "quick start" in the README it's perfect :smile:

**Comment by fogfish** [comment]
done (see #112)
