### ISSUE TITLE
Saving a scenario with numeric ID fails

### ISSUE THREAD

**Issue by hjacobs** [zalando/typhoon#107]
Trying to create a scenario with a numeric ID like 123 fails on save, i.e. "Save" on http://localhost:8080/dashboard/editor/123 does not do anything. I ran into this problem during my first try, it worked afterwards when using a scenario ID of "test".

I used the Docker image version 0.8.1-2 (56d old).

**Comment by fogfish** [comment]
This is a valid behavior!
> Each load scenario is valid Erlang module.

The numeric modules are not supported. It shall be prefixed with id123. We can make automatic prefixing but I do not like it. It became a confusing... However, this is a valid concern that UI should guide you to right naming.

**Comment by hjacobs** [comment]
Yes, it's mostly about usability --- the UI should not allow getting stuck --- I don't care about "Erlang modules" as a first time Typhoon user :smirk:

**Comment by fogfish** [comment]
fixed.
