### ISSUE TITLE
Not able to use the UI?

### ISSUE THREAD

**Issue by hjacobs** [zalando/typhoon#122]
Just tried out the fresh 1.0.1 release via Docker and I'm really stuck in the UI. How do I save and launch my new scenario? (only the "Hide" link is clickable)

I'm really feeling stupid...

![screenshot_2017-04-12_22-25-35](https://cloud.githubusercontent.com/assets/510328/24977907/0d7aeb82-1fcf-11e7-9f34-44a2f70e997f.png)

**Comment by fogfish** [comment]
click (x) cross to hide editor.

**Comment by hjacobs** [comment]
Does not work for me, now I get a small error icon..

![screenshot_2017-04-12_22-28-32](https://cloud.githubusercontent.com/assets/510328/24978034/70be24de-1fcf-11e7-8a72-f379b3c062a4.png)

**Comment by fogfish** [comment]
Thank you to be a brave user of new UI. Looks like a bit of polishing is needed.
It complains to you that scenario id is not defined.
```
-module(abc123).
```

**Comment by fogfish** [comment]
PR #123 should address some of issue raised here.

**Comment by fogfish** [comment]
fixed via #123
