### ISSUE TITLE
docker image - latest tag does not exist

### ISSUE THREAD

**Issue by mduesterhoeft** [zalando/typhoon#144]
The documentation proposes to use `registry.opensource.zalan.do/hunt/typhoon:latest` but there seems to be no `latest` tag. 

So `docker run -it --name typhoon --rm -p 8080:8080 registry.opensource.zalan.do/hunt/typhoon:latest` does not work while `docker run -it --name typhoon --rm -p 8080:8080 registry.opensource.zalan.do/hunt/typhoon:1.0.2` does.

See https://registry.opensource.zalan.do/v2/hunt/typhoon/tags/list

**Comment by hjacobs** [comment]
Our [Pier One Docker registry](https://github.com/zalando-stups/pierone) supports "latest" as a virtual/fake tag, so it does not really exist, but will give you the latest version on `docker pull`. The "tags/list" URL will therefore not show the tag, but it should work with `docker pull` (and it does for me with latest "docker-ce" on Ubuntu).

**Comment by hjacobs** [comment]
Background: our Docker registry enforces immutable tags, i.e. it does not allow overwriting a tag with different contents (unlike the official Docker registry / Docker Hub).

**Comment by mduesterhoeft** [comment]
Thanks for the information. Strangely it did not work for me with `latest` on docker for mac 17.06.0-ce

**Comment by hjacobs** [comment]
@mduesterhoeft: could you try `docker pull registry.opensource.zalan.do/stups/ubuntu:latest` to check whether it is a general problem or specific to Typhoon?

**Comment by mduesterhoeft** [comment]
that works 🤔

**Comment by fogfish** [comment]
It works for me ™️ 
I believe it relates to the version of docker client or some temporary glitch at matrix.
Mine docker version is
```
docker --version
Docker version 17.03.1-ce, build c6d412e
```

**Comment by fogfish** [comment]
btw, use 1.0.2-5

**Comment by mduesterhoeft** [comment]
Sadly also `docker run -it --name typhoon --rm -p 8080:8080 registry.opensource.zalan.do/hunt/typhoon:1.0.2-5` while `docker run -it --name typhoon --rm -p 8080:8080 registry.opensource.zalan.do/hunt/typhoon:1.0.2` works .

**Comment by fogfish** [comment]
Sad story... It looks like a bug at `registry.opensource.zalan.do` or your client is not compatible. 
Unfortunately, I am not able to help here anyhow. I hope @hjacobs can help to debug it.

Alternative, try to assemble the image from source... I am going to change the hosting provider once I back to business.

**Comment by hjacobs** [comment]
Works for me too ™️ :

```
$ docker run -it --name typhoon --rm -p 8080:8080 registry.opensource.zalan.do/hunt/typhoon:latest
Unable to find image 'registry.opensource.zalan.do/hunt/typhoon:latest' locally
Pulling repository registry.opensource.zalan.do/hunt/typhoon
388de1a3432d: Pulling image (latest) from registry.opensource.zalan.do/hunt/typh388de1a3432d: Pulling image (latest) from registry.opensource.zalan.do/hunt/typh388de1a3432d: Pull complete 
b51149973e6a: Pull complete 
91ffa8cdda05: Pull complete 
e4129192f8bd: Pull complete 
b278161c3550: Pull complete 
c6f50730ca65: Pull complete 
Status: Downloaded newer image for registry.opensource.zalan.do/hunt/typhoon:latest
registry.opensource.zalan.do/hunt/typhoon: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
Exec: /usr/local/typhoon-1.0.2-5/erts-8.2/bin/erlexec -noshell -noinput +Bd -boot /usr/local/typhoon-1.0.2-5/releases/1.0.2-5/start -mode embedded -config /usr/local/typhoon-1.0.2-5/releases/1.0.2-5/sys.config -boot_var ERTS_LIB_DIR /usr/local/typhoon-1.0.2-5/erts-8.2/../lib -args_file /usr/local/typhoon-1.0.2-5/releases/1.0.2-5/vm.args -- foreground
Root: /usr/local/typhoon-1.0.2-5
heart_beat_kill_pid = 13
^Cheart: Thu Jul 13 10:23:23 2017: Erlang has closed.
heart: Thu Jul 13 10:23:23 2017: Would reboot. Terminating.
~ $ ^C
~ $ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Not sure how I can now help to fix it...

**Comment by mduesterhoeft** [comment]
I think it is not too important for me - I did not receive the error with `17.03.0-ce` btw.

Thanks.

**Comment by hjacobs** [comment]
OK, closing :smile:
