### ISSUE TITLE
abort the load once scenario is deleted

### ISSUE THREAD

**Issue by fogfish** [zalando/typhoon#22]
1. create and publish scenario using `curl -v -XPUT http://127.0.0.1:8080/scenario/xxx`
2. spawn the load `curl -v -XGET http://127.0.0.1:8080/scenario/xxx/spawn`
3. delete scenario once load is active  `curl -v -XDELETE http://127.0.0.1:8080/scenario/xxx`

It is expected that load is aborted.

**Comment by LappleApple** [comment]
@fogfish Same question; something we should add to our backlog and meanwhile add a "Help wanted" label?

**Comment by fogfish** [comment]
The issue is resolvable using a right definitions as load scenarios.

**Comment by fogfish** [comment]
fixed at release 1.0.0
