### ISSUE TITLE
check LevelDB dependencies. 

### ISSUE THREAD

**Issue by fogfish** [zalando/typhoon#54]
LeveDB causad a build failure at Travis. 

make[1]: Leaving directory `/home/travis/build/zalando/typhoon/_build/default/lib/eleveldb/c_src/leveldb'
===> Compiling c_src/eleveldb.cc
===> Compiling /home/travis/build/zalando/typhoon/c_src/refobjects.cc
===> c_src/leveldb/util/refobject_base.h: In member function ‘void eleveldb::ErlRefObject::InitiateCloseRequest()’:
c_src/leveldb/util/refobject_base.h:56:23: error: ‘volatile uint32_t leveldb::RefObjectBase::m_RefCount’ is private
/home/travis/build/zalando/typhoon/c_src/refobjects.cc:108:15: error: within this context
c_src/leveldb/util/refobject_base.h: In member function ‘virtual uint32_t eleveldb::ErlRefObject::RefDec()’:
c_src/leveldb/util/refobject_base.h:56:23: error: ‘volatile uint32_t leveldb::RefObjectBase::m_RefCount’ is private
/home/travis/build/zalando/typhoon/c_src/refobjects.cc:130:43: error: within this context
c_src/leveldb/util/refobject_base.h:56:23: error: ‘volatile uint32_t leveldb::RefObjectBase::m_RefCount’ is private
/home/travis/build/zalando/typhoon/c_src/refobjects.cc:140:21: error: within this context

**Comment by fogfish** [comment]
fixed (due to dependencies).

**Comment by zhjunqin** [comment]
I met same problem in another project, could you help tell me how you fix this, thanks a lot!

**Comment by fogfish** [comment]
I've used old version on eleveldb, take the latest one. I would also recommend to migrate to rebar3, it has very handy pc plugin
https://github.com/zalando/typhoon/blob/master/rebar.config#L117

**Comment by zhjunqin** [comment]
I see, thank you.
