### ISSUE TITLE
Help on User Experience 

### ISSUE THREAD

**Issue by fogfish** [zalando/typhoon#62]
# Background

The time-series data visualization crisis is well depicted by [Mike Bostock](https://bost.ocks.org/mike/cubism/intro/#0). The usage of the proposed visualization technique cubism.js improves readability and the analysis of latencies reported by the tool. We are looking for highly adoptable and customizable visualization, preferably based on D3. We used bootstrap framework to build wireframes around time series visualization using single page application. 

You can find attempts here:
https://github.com/zalando/typhoon/tree/master/apps/zephyrus/priv/htdoc
# Challenge

The better User Experience is required. I see the usage of the tool in following context:
- Real-time analysis and management of scenarios
- Analysis of historical data (previously executed scenario's)
- Sharing of results with team(s) as reports that highlights major pain points and anomalies
- Built-in editor of scenario(s) possibly with syntax highlights and auto-complete

Any wireframes or bootstrap examples would benefit project development.

**Comment by LappleApple** [comment]
Hey @fogfish, so I'm clear: You'd like UX experience with these four bulleted items?

**Comment by fogfish** [comment]
Yes, these bullets defines a major user flows within the tool. I am afraid that they are optimal for usability. Any feedback on usability, graphical design and bootstrap wireframes are welcome.

**Comment by fogfish** [comment]
Based on my research. I've came up with a short list defined here
https://colorlib.com/wp/free-bootstrap-admin-dashboard-templates/

I'll procedure with Lumina Admin template in near future unless I get other proposals here.

**Comment by fogfish** [comment]
done
