### ISSUE TITLE
Clean-up documentation

### ISSUE THREAD

**Issue by fogfish** [zalando/typhoon#85]
## clean-up

1. README: depict new user interface
1. Load scenario syntax (doc/scenario.md)
1. Check installation instruction (doc/install.md)
1. restapi.yaml
1. architecture (doc/arch.md)
1. howto

## remove
1. config instructions (move to install.md)

**Comment by fogfish** [comment]
@LappleApple Can you help with this issue?

**Comment by inikolaev** [comment]
@fogfish would be nice to have some documentation on how to run application from source code. I tried compiling and running it in Docker container yesterday, but I couldn't make HTTP server to work.

**Comment by fogfish** [comment]
@inikolaev here we have an install guide https://github.com/zalando/typhoon/blob/master/docs/install.md

I believe we can extend it with RnD chapter

**Comment by fogfish** [comment]
fixed at release 1.0.0
